const actionTypes = {
  USER_FETCHING:'USER_FETCHING',
  USER_SUCCESS:'USER_SUCCESS',
  USER_ERROR:'USER_ERROR',
  USER_REPO_FECHING:'USER_REPO_FECHING',
  USER_REPO_SUCCESS:'USER_REPO_SUCCESS',
  USER_REPO_ERROR:'USER_REPO_ERROR',
  SORT_ASC: 'SORT_ASC',
  SORT_DSC: 'SORT_DSC',
  SORT_RANK_ASC: 'SORT_RANK_ASC',
  SORT_RANK_DSC: 'SORT_RANK_DSC',
}

export default actionTypes;